import React, { createContext, useContext, useState, ReactNode } from 'react';


type Language = 'fr' | 'en' | 'ar' | 'zgh';

interface Translations {
  [key: string]: string | Translations;
}

const translations: Record<Language, Translations> = {
  fr: {
    common: {
      search: 'Rechercher',
      save: 'Enregistrer',
      cancel: 'Annuler',
      delete: 'Supprimer',
      edit: 'Modifier',
      create: 'Créer',
      view: 'Voir',
      back: 'Retour',
      loading: 'Chargement...',
      noResults: 'Aucun résultat',
      actions: 'Actions',
      confirm: 'Confirmer',
      yes: 'Oui',
      no: 'Non',
      all: 'Tous',
      status: 'Statut',
      date: 'Date',
      name: 'Nom',
      email: 'Email',
      members: 'Membres',
      participants: 'Participants',
      details: 'Détails',
      description: 'Description',
      places: 'Places',
      available: 'disponibles',
    },
    nav: {
      dashboard: 'Tableau de bord',
      profile: 'Mon profil',
      clubs: 'Clubs',
      activities: 'Activités',
      users: 'Utilisateurs',
      admin: 'Administration',
      calendar: 'Calendrier',
      logout: 'Déconnexion',
    },
    auth: {
      login: 'Connexion',
      logout: 'Déconnexion',
      email: 'Adresse email',
      password: 'Mot de passe',
      forgotPassword: 'Mot de passe oublié ?',
      loginButton: 'Se connecter',
      welcome: 'Bienvenue sur Campus Life',
      subtitle: 'Connectez-vous pour accéder à votre espace',
      errors: {
        invalid_credentials: 'Email ou mot de passe incorrect',
        required_email: 'L\'email est requis',
        required_password: 'Le mot de passe est requis',
        invalid_email: 'Email invalide',
      },
    },
    dashboard: {
      title: 'Tableau de bord',
      welcome: 'Bienvenue',
      students: 'Étudiants',
      clubs: 'Clubs',
      activities: 'Activités',
      registrations: 'Inscriptions',
      recentActivities: 'Activités récentes',
      popularClubs: 'Clubs populaires',
      upcomingEvents: 'Événements à venir',
      stats: 'Statistiques',
      thisMonth: 'Ce mois',
      thisWeek: 'Cette semaine',
      evolution: 'Évolution des inscriptions',
      distribution: 'Répartition par type',
      stats_title: 'Statistiques',
    },
    profile: {
      title: 'Mon profil',
      personalInfo: 'Informations personnelles',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Email',
      program: 'Filière',
      year: 'Année',
      myClubs: 'Mes clubs',
      myActivities: 'Mes activités',
      editProfile: 'Modifier le profil',
      changePhoto: 'Changer la photo',
    },
    clubs: {
      title: 'Clubs',
      createClub: 'Créer un club',
      allClubs: 'Tous les clubs',
      myClubs: 'Mes clubs',
      validated: 'Validé',
      pending: 'En attente',
      members: 'membres',
      activities: 'activités',
      joinClub: 'Rejoindre',
      leaveClub: 'Quitter',
      viewDetails: 'Voir détails',
      manager: 'Responsable',
      joinRequests: 'Demandes d\'adhésion',
      approve: 'Approuver',
      reject: 'Rejeter',
      noClubs: 'Aucun club trouvé',
      searchPlaceholder: 'Rechercher un club...',
      filterValidated: 'Clubs validés',
      filterPending: 'Clubs en attente',
    },
    activities: {
      title: 'Activités',
      createActivity: 'Créer une activité',
      allActivities: 'Toutes les activités',
      myActivities: 'Mes activités',
      upcoming: 'À venir',
      past: 'Passées',
      register: 'S\'inscrire',
      unregister: 'Se désinscrire',
      viewDetails: 'Voir détails',
      date: 'Date',
      time: 'Heure',
      location: 'Lieu',
      organizer: 'Organisateur',
      participants: 'participants',
      placesLeft: 'places restantes',
      full: 'Complet',
      noActivities: 'Aucune activité trouvée',
      searchPlaceholder: 'Rechercher une activité...',
      exportPdf: 'Exporter PDF',
      exportCsv: 'Exporter CSV',
    },
    users: {
      title: 'Gestion des utilisateurs',
      allUsers: 'Tous les utilisateurs',
      students: 'Étudiants',
      managers: 'Responsables',
      admins: 'Administrateurs',
      active: 'Actif',
      blocked: 'Bloqué',
      block: 'Bloquer',
      unblock: 'Débloquer',
      viewProfile: 'Voir profil',
      searchPlaceholder: 'Rechercher un utilisateur...',
    },
    admin: {
      title: 'Administration',
      platformStats: 'Statistiques de la plateforme',
      pendingClubs: 'Clubs en attente',
      validateClub: 'Valider',
      deleteClub: 'Supprimer',
      reportedActivities: 'Activités signalées',
      systemSettings: 'Paramètres système',
    },
    errors: {
      accessDenied: 'Accès refusé',
      accessDeniedMessage: 'Vous n\'avez pas les permissions nécessaires pour accéder à cette page.',
      pageNotFound: 'Page introuvable',
      pageNotFoundMessage: 'La page que vous recherchez n\'existe pas.',
      backHome: 'Retour à l\'accueil',
    },
    roles: {
      student: 'Étudiant',
      club_manager: 'Responsable de club',
      admin: 'Administrateur',
    },
  },
  en: {
    common: {
      search: 'Search',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      create: 'Create',
      view: 'View',
      back: 'Back',
      loading: 'Loading...',
      noResults: 'No results',
      actions: 'Actions',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
      all: 'All',
      status: 'Status',
      date: 'Date',
      name: 'Name',
      email: 'Email',
      members: 'Members',
      participants: 'Participants',
      details: 'Details',
      description: 'Description',
      places: 'Places',
      available: 'available',
    },
    nav: {
      dashboard: 'Dashboard',
      profile: 'My Profile',
      clubs: 'Clubs',
      activities: 'Activities',
      users: 'Users',
      admin: 'Administration',
      calendar: 'Calendar',
      logout: 'Logout',
    },
    auth: {
      login: 'Login',
      logout: 'Logout',
      email: 'Email address',
      password: 'Password',
      forgotPassword: 'Forgot password?',
      loginButton: 'Sign in',
      welcome: 'Welcome to Campus Life',
      subtitle: 'Sign in to access your space',
      errors: {
        invalid_credentials: 'Invalid email or password',
        required_email: 'Email is required',
        required_password: 'Password is required',
        invalid_email: 'Invalid email',
      },
    },
    dashboard: {
      title: 'Dashboard',
      welcome: 'Welcome',
      students: 'Students',
      clubs: 'Clubs',
      activities: 'Activities',
      registrations: 'Registrations',
      recentActivities: 'Recent Activities',
      popularClubs: 'Popular Clubs',
      upcomingEvents: 'Upcoming Events',
      stats: 'Statistics',
      thisMonth: 'This month',
      thisWeek: 'This week',
      evolution: 'Registration Evolution',
      distribution: 'Distribution by Type',
      stats_title: 'Statistics',
    },
    profile: {
      title: 'My Profile',
      personalInfo: 'Personal Information',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      program: 'Program',
      year: 'Year',
      myClubs: 'My Clubs',
      myActivities: 'My Activities',
      editProfile: 'Edit Profile',
      changePhoto: 'Change Photo',
    },
    clubs: {
      title: 'Clubs',
      createClub: 'Create Club',
      allClubs: 'All Clubs',
      myClubs: 'My Clubs',
      validated: 'Validated',
      pending: 'Pending',
      members: 'members',
      activities: 'activities',
      joinClub: 'Join',
      leaveClub: 'Leave',
      viewDetails: 'View Details',
      manager: 'Manager',
      joinRequests: 'Join Requests',
      approve: 'Approve',
      reject: 'Reject',
      noClubs: 'No clubs found',
      searchPlaceholder: 'Search for a club...',
      filterValidated: 'Validated clubs',
      filterPending: 'Pending clubs',
    },
    activities: {
      title: 'Activities',
      createActivity: 'Create Activity',
      allActivities: 'All Activities',
      myActivities: 'My Activities',
      upcoming: 'Upcoming',
      past: 'Past',
      register: 'Register',
      unregister: 'Unregister',
      viewDetails: 'View Details',
      date: 'Date',
      time: 'Time',
      location: 'Location',
      organizer: 'Organizer',
      participants: 'participants',
      placesLeft: 'places left',
      full: 'Full',
      noActivities: 'No activities found',
      searchPlaceholder: 'Search for an activity...',
      exportPdf: 'Export PDF',
      exportCsv: 'Export CSV',
    },
    users: {
      title: 'User Management',
      allUsers: 'All Users',
      students: 'Students',
      managers: 'Managers',
      admins: 'Administrators',
      active: 'Active',
      blocked: 'Blocked',
      block: 'Block',
      unblock: 'Unblock',
      viewProfile: 'View Profile',
      searchPlaceholder: 'Search for a user...',
    },
    admin: {
      title: 'Administration',
      platformStats: 'Platform Statistics',
      pendingClubs: 'Pending Clubs',
      validateClub: 'Validate',
      deleteClub: 'Delete',
      reportedActivities: 'Reported Activities',
      systemSettings: 'System Settings',
    },
    errors: {
      accessDenied: 'Access Denied',
      accessDeniedMessage: 'You do not have permission to access this page.',
      pageNotFound: 'Page Not Found',
      pageNotFoundMessage: 'The page you are looking for does not exist.',
      backHome: 'Back to Home',
    },
    roles: {
      student: 'Student',
      club_manager: 'Club Manager',
      admin: 'Administrator',
    },
  },
  ar: {
    common: {
      search: 'بحث',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      create: 'إنشاء',
      view: 'عرض',
      back: 'رجوع',
      loading: 'جاري التحميل...',
      noResults: 'لا توجد نتائج',
      actions: 'إجراءات',
      confirm: 'تأكيد',
      yes: 'نعم',
      no: 'لا',
      all: 'الكل',
      status: 'الحالة',
      date: 'التاريخ',
      name: 'الاسم',
      email: 'البريد الإلكتروني',
      members: 'أعضاء',
      participants: 'مشتركين',
      details: 'تفاصيل',
      description: 'وصف',
      places: 'أماكن',
      available: 'متاح',
    },
    nav: {
      dashboard: 'لوحة التحكم',
      profile: 'ملفي الشخصي',
      clubs: 'الأندية',
      activities: 'الأنشطة',
      users: 'المستخدمين',
      admin: 'الإدارة',
      calendar: 'التقويم',
      logout: 'تسجيل الخروج',
    },
    auth: {
      login: 'تسجيل الدخول',
      logout: 'تسجيل الخروج',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      forgotPassword: 'نسيت كلمة المرور؟',
      loginButton: 'دخول',
      welcome: 'مرحباً بك في Campus Life',
      subtitle: 'سجل الدخول للوصول إلى مساحتك',
      errors: {
        invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
        required_email: 'البريد الإلكتروني مطلوب',
        required_password: 'كلمة المرور مطلوبة',
        invalid_email: 'بريد إلكتروني غير صالح',
      },
    },
    dashboard: {
      title: 'لوحة التحكم',
      welcome: 'مرحباً',
      students: 'الطلاب',
      clubs: 'الأندية',
      activities: 'الأنشطة',
      registrations: 'التسجيلات',
      recentActivities: 'أنشطة حديثة',
      popularClubs: 'أندية شائعة',
      upcomingEvents: 'أحداث قادمة',
      stats: 'الإحصائيات',
      thisMonth: 'هذا الشهر',
      thisWeek: 'هذا الأسبوع',
      evolution: 'تطور التسجيل',
      distribution: 'التوزيع حسب النوع',
      stats_title: 'الإحصائيات',
    },
    profile: {
      title: 'ملفي الشخصي',
      personalInfo: 'معلومات شخصية',
      firstName: 'الاسم الأول',
      lastName: 'الاسم الأخير',
      email: 'البريد الإلكتروني',
      program: 'التخصص',
      year: 'السنة',
      myClubs: 'أنديتي',
      myActivities: 'أنشطتي',
      editProfile: 'تعديل الملف الشخصي',
      changePhoto: 'تغيير الصورة',
    },
    clubs: {
      title: 'الأندية',
      createClub: 'إنشاء نادي',
      allClubs: 'كل الأندية',
      myClubs: 'أنديتي',
      validated: 'مقبول',
      pending: 'قيد الانتظار',
      members: 'أعضاء',
      activities: 'أنشطة',
      joinClub: 'انضمام',
      leaveClub: 'مغادرة',
      viewDetails: 'عرض التفاصيل',
      manager: 'المسؤول',
      joinRequests: 'طلبات الانضمام',
      approve: 'قبول',
      reject: 'رفض',
      noClubs: 'لا توجد أندية',
      searchPlaceholder: 'البحث عن نادي...',
      filterValidated: 'أندية مقبولة',
      filterPending: 'أندية قيد الانتظار',
    },
    activities: {
      title: 'الأنشطة',
      createActivity: 'إنشاء نشاط',
      allActivities: 'كل الأنشطة',
      myActivities: 'أنشطتي',
      upcoming: 'قادمة',
      past: 'سابقة',
      register: 'تسجيل',
      unregister: 'إلغاء التسجيل',
      viewDetails: 'عرض التفاصيل',
      date: 'التاريخ',
      time: 'الوقت',
      location: 'المكان',
      organizer: 'المنظم',
      participants: 'مشتركين',
      placesLeft: 'أماكن متبقية',
      full: 'ممتلئ',
      noActivities: 'لا توجد أنشطة',
      searchPlaceholder: 'البحث عن نشاط...',
      exportPdf: 'تصدير PDF',
      exportCsv: 'تصدير CSV',
    },
    users: {
      title: 'إدارة المستخدمين',
      allUsers: 'كل المستخدمين',
      students: 'الطلاب',
      managers: 'المسؤولين',
      admins: 'المسؤولين',
      active: 'نشط',
      blocked: 'محظور',
      block: 'حظر',
      unblock: 'إلغاء الحظر',
      viewProfile: 'عرض الملف الشخصي',
      searchPlaceholder: 'البحث عن مستخدم...',
    },
    admin: {
      title: 'الإدارة',
      platformStats: 'إحصائيات المنصة',
      pendingClubs: 'أندية قيد الانتظار',
      validateClub: 'قبول',
      deleteClub: 'حذف',
      reportedActivities: 'أنشطة مبلغ عنها',
      systemSettings: 'إعدادات النظام',
    },
    errors: {
      accessDenied: 'تم رفض الوصول',
      accessDeniedMessage: 'ليس لديك الصلاحيات اللازمة للوصول إلى هذه الصفحة.',
      pageNotFound: 'الصفحة غير موجودة',
      pageNotFoundMessage: 'الصفحة التي تبحث عنها غير موجودة.',
      backHome: 'العودة للرئيسية',
    },
    roles: {
      student: 'طالب',
      club_manager: 'مدير نادي',
      admin: 'مسؤول',
    },
  },
  zgh: {
    common: {
      search: 'ⴰⵔⵣⵣⵓ',
      save: 'ⵙⵊⵊⵍ',
      cancel: 'ⵙⵔ',
      delete: 'ⴽⴽⵙ',
      edit: 'ⵙⵏⴼⵍ',
      create: 'ⵙⴽⵔ',
      view: 'ⵥⵕ',
      back: 'ⴰⵖⵓⵍ',
      loading: 'ⴰⵣⵓⴳⵣ...',
      noResults: 'ⵓⵍⴰ ⴰⵢⵏⵏⴰ',
      actions: 'ⵜⵉⴳⴰⵡⵉⵏ',
      confirm: 'ⵙⵙⵎⵖⵔ',
      yes: 'ⵢⴰⵀ',
      no: 'ⵓⵀⵓ',
      all: 'ⴽⵓⵍⵍⵓ',
      status: 'ⴰⴷⴷⴰⴷ',
      date: 'ⴰⵙⴰⴽⵓⴷ',
      name: 'ⵉⵙⵎ',
      email: 'ⵉⵎⴰⵢⵍ',
      members: 'ⵉⵎⵙⵍⴰⵢⵏ',
      participants: 'ⵉⵎⴷⵔⴰⵡⵏ',
      details: 'ⵜⵉⴼⵔⴽⵉⵡⵉⵏ',
      description: 'ⴰⴳⵍⴰⵎ',
      places: 'ⵉⴷⵖⴰⵔⵏ',
      available: 'ⵍⵍⴰⵏ',
    },
    nav: {
      dashboard: 'ⴰⴳⴰⴷⵉⵔ ⵏ ⵓⵙⵏⵓⴱⴳ',
      profile: 'ⴰⵎⴰⴳ',
      clubs: 'ⵜⵉⵎⵙⵎⵓⵏⵉⵏ',
      activities: 'ⵉⵎⵓⵙⵙⵓⵜⵏ',
      users: 'ⵉⵎⵙⵙⵎⵔⵙⵏ',
      admin: 'ⵜⴰⵎⵀⵍⴰ',
      calendar: 'ⴰⵡⵉⵜⴰⵢ',
      logout: 'ⴼⴼⵖ',
    },
    auth: {
      login: 'ⴽⵛⵎ',
      logout: 'ⴼⴼⵖ',
      email: 'ⵉⵎⴰⵢⵍ',
      password: 'ⵜⴰⴳⵓⵔⵉ ⵏ ⵓⵣⵔⴰⵢ',
      forgotPassword: 'ⵜⵜⵓⵖ ⵜⴰⴳⵓⵔⵉ ⵏ ⵓⵣⵔⴰⵢ?',
      loginButton: 'ⴽⵛⵎ',
      welcome: 'ⴰⵏⵙⵓⴼ ⴳ Campus Life',
      subtitle: 'ⴽⵛⵎ ⴰⴼⴰⴷ ⴰⴷ ⵜⵣⵔⴷ ⵖⵔ ⵜⴰⵙⴳⴰ ⵏⵏⴽ',
      errors: {
        invalid_credentials: 'ⵉⵎⴰⵢⵍ ⵏⵖⴷ ⵜⴰⴳⵓⵔⵉ ⵏ ⵓⵣⵔⴰⵢ ⵓⵔ ⵖⴷⵉⵏ',
        required_email: 'ⵉⵎⴰⵢⵍ ⵉⴳⴰ ⴰⵣⵣⵔⴰⴼ',
        required_password: 'ⵜⴰⴳⵓⵔⵉ ⵏ ⵓⵣⵔⴰⵢ ⵜⴳⴰ ⵜⴰⵣⵣⵔⴰⴼⵜ',
        invalid_email: 'ⵉⵎⴰⵢⵍ ⵓⵔ ⵉⵖⴷⵉ',
      },
    },
    dashboard: {
      title: 'ⴰⴳⴰⴷⵉⵔ ⵏ ⵓⵙⵏⵓⴱⴳ',
      welcome: 'ⴰⵏⵙⵓⴼ',
      students: 'ⵉⵏⵍⵎⴰⴷⵏ',
      clubs: 'ⵜⵉⵎⵙⵎⵓⵏⵉⵏ',
      activities: 'ⵉⵎⵓⵙⵙⵓⵜⵏ',
      registrations: 'ⵉⵣⵎⵎⴻⵎⵏ',
      recentActivities: 'ⵉⵎⵓⵙⵙⵓⵜⵏ ⵉⵎⴰⵢⵏⵓⵜⵏ',
      popularClubs: 'ⵜⵉⵎⵙⵎⵓⵏⵉⵏ ⵜⵉⵎⵓⵙⵙⵏⴰⵡⵉⵏ',
      upcomingEvents: 'ⵉⵎⵓⵙⵙⵓⵜⵏ ⴷ ⵉⴷⴷⴰⵏ',
      stats: 'ⵜⵉⵙⵎⴽⵜⴰ',
      thisMonth: 'ⴰⵢⵢⵓⵔ ⴰⴷ',
      thisWeek: 'ⵉⵎⴰⵍⴰⵙⵙ ⴰⴷ',
      evolution: 'ⵜⴰⵎⵀⵍⴰ ⵏ ⵓⵣⵎⵎⴻⵎ',
      distribution: 'ⴰⴱⵟⵟⵓ ⵙ ⵡⴰⵏⴰⵡ',
      stats_title: 'ⵜⵉⵙⵎⴽⵜⴰ',
    },
    profile: {
      title: 'ⴰⵎⴰⴳ ⵉⵏⵓ',
      personalInfo: 'ⵜⵓⵎⵍⴰⵢⵉⵏ ⵜⵓⴷⵎⴰⵡⵉⵏ',
      firstName: 'ⵉⵙⵎ',
      lastName: 'ⵜⴰⵏⴽⵔ',
      email: 'ⵉⵎⴰⵢⵍ',
      program: 'ⴰⵙⴽⴽⵉⵏ',
      year: 'ⴰⵙⴳⴳⵯⴰⵙ',
      myClubs: 'ⵜⵉⵎⵙⵎⵓⵏⵉⵏ ⵉⵏⵓ',
      myActivities: 'ⵉⵎⵓⵙⵙⵓⵜⵏ ⵉⵏⵓ',
      editProfile: 'ⵙⵏⴼⵍ ⴰⵎⴰⴳ',
      changePhoto: 'ⵙⵏⴼⵍ ⵜⴰⵡⵍⴰⴼⵜ',
    },
    clubs: {
      title: 'ⵜⵉⵎⵙⵎⵓⵏⵉⵏ',
      createClub: 'ⵙⴽⵔ ⵜⴰⵎⵙⵎⵓⵏⵜ',
      allClubs: 'ⴽⵓⵍⵍⵓ ⵜⵉⵎⵙⵎⵓⵏⵉⵏ',
      myClubs: 'ⵜⵉⵎⵙⵎⵓⵏⵉⵏ ⵉⵏⵓ',
      validated: 'ⵉⵜⵜⵓⵙⵖⵣⵏ',
      pending: 'ⵉⵜⵜⵓⵔⵊⴰ',
      members: 'ⵉⵎⵙⵍⴰⵢⵏ',
      activities: 'ⵉⵎⵓⵙⵙⵓⵜⵏ',
      joinClub: 'ⴰⴷⴼ',
      leaveClub: 'ⴼⴼⵖ',
      viewDetails: 'ⵥⵕ ⵜⵉⴼⵔⴽⵉⵡⵉⵏ',
      manager: 'ⴰⵎⵙⵜⴳⴳⴰⵔ',
      joinRequests: 'ⵜⵓⵜⵔⵉⵡⵉⵏ ⵏ ⵡⴰⴷⴰⴼ',
      approve: 'ⵇⴱⵍ',
      reject: 'ⴰⴳⵉ',
      noClubs: 'ⵓⵔ ⵜⵍⵍⵉ ⴽⵔⴰ ⵏ ⵜⵎⵙⵎⵓⵏⵜ',
      searchPlaceholder: 'ⵔⵣⵣⵓ ⴼ ⵜⵎⵙⵎⵓⵏⵜ...',
      filterValidated: 'ⵜⵉⵎⵙⵎⵓⵏⵉⵏ ⵉⵜⵜⵓⵙⵖⵣⵏⵏ',
      filterPending: 'ⵜⵉⵎⵙⵎⵓⵏⵉⵏ ⵉⵜⵜⵓⵔⵊⴰⵏ',
    },
    activities: {
      title: 'ⵉⵎⵓⵙⵙⵓⵜⵏ',
      createActivity: 'ⵙⴽⵔ ⴰⵎⵓⵙⵙⵓ',
      allActivities: 'ⴽⵓⵍⵍⵓ ⵉⵎⵓⵙⵙⵓⵜⵏ',
      myActivities: 'ⵉⵎⵓⵙⵙⵓⵜⵏ ⵉⵏⵓ',
      upcoming: 'ⴷ ⵉⴷⴷⴰⵏ',
      past: 'ⵉⵣⵔⵉⵏ',
      register: 'ⵣⵎⵎⴻⵎ',
      unregister: 'ⴽⴽⵙ ⴰⵣⵎⵎⴻⵎ',
      viewDetails: 'ⵥⵕ ⵜⵉⴼⵔⴽⵉⵡⵉⵏ',
      date: 'ⴰⵙⴰⴽⵓⴷ',
      time: 'ⴰⴽⵓⴷ',
      location: 'ⴰⴷⵖⴰⵔ',
      organizer: 'ⴰⵎⵙⵏⵎⴰⵍⴰ',
      participants: 'ⵉⵎⴷⵔⴰⵡⵏ',
      placesLeft: 'ⵉⴷⵖⴰⵔⵏ ⵉⵙⵓⵍⵏ',
      full: 'ⵉⵜⵜⵓⵎⵔ',
      noActivities: 'ⵓⵔ ⵉⵍⵍⵉ ⴽⵔⴰ ⵏ ⵓⵎⵓⵙⵙⵓ',
      searchPlaceholder: 'ⵔⵣⵣⵓ ⴼ ⵓⵎⵓⵙⵙⵓ...',
      exportPdf: 'ⵙⵙⵓⴼⵖ PDF',
      exportCsv: 'ⵙⵙⵓⴼⵖ CSV',
    },
    users: {
      title: 'ⴰⵙⵡⵓⴷⴷⵓ ⵏ ⵉⵎⵙⵙⵎⵔⵙⵏ',
      allUsers: 'ⴽⵓⵍⵍⵓ ⵉⵎⵙⵙⵎⵔⵙⵏ',
      students: 'ⵉⵏⵍⵎⴰⴷⵏ',
      managers: 'ⵉⵎⵙⵜⴳⴳⴰⵔⵏ',
      admins: 'ⵉⵎⵙⵙⵓⴳⵓⵔⵏ',
      active: 'ⴰⵎⵓⵙⵙⵓ',
      blocked: 'ⵉⵜⵜⵓⴳⴷⵍ',
      block: 'ⴳⴷⵍ',
      unblock: 'ⴽⴽⵙ ⴰⴳⴷⵍ',
      viewProfile: 'ⵥⵕ ⴰⵎⴰⴳ',
      searchPlaceholder: 'ⵔⵣⵣⵓ ⴼ ⵓⵎⵙⵙⵎⵔⵙ...',
    },
    admin: {
      title: 'ⵜⴰⵎⵀⵍⴰ',
      platformStats: 'ⵜⵉⵙⵎⴽⵜⴰ ⵏ ⵓⵙⴰⵢⵔⴰⵔ',
      pendingClubs: 'ⵜⵉⵎⵙⵎⵓⵏⵉⵏ ⵉⵜⵜⵓⵔⵊⴰⵏ',
      validateClub: 'ⵙⵖⵣⵏ',
      deleteClub: 'ⴽⴽⵙ',
      reportedActivities: 'ⵉⵎⵓⵙⵙⵓⵜⵏ ⵉⵜⵜⵓⵙⵏⴰⵍⵏ',
      systemSettings: 'ⵉⵙⵖⴰⵍⵏ ⵏ ⵓⵏⴳⵔⴰⵡ',
    },
    errors: {
      accessDenied: 'ⴰⴷⴰⴼ ⵉⵜⵜⵓⴳⴷⵍ',
      accessDeniedMessage: 'ⵓⵔ ⴷⴰⵔⴽ ⵉⵣⵔⴼⴰⵏ ⴰⴼⴰⴷ ⴰⴷ ⵜⴽⵛⵎⴷ ⵖⵔ ⵜⴰⵙⵏⴰ ⴰⴷ.',
      pageNotFound: 'ⵜⴰⵙⵏⴰ ⵓⵔ ⵜⵍⵍⵉ',
      pageNotFoundMessage: 'ⵜⴰⵙⵏⴰ ⵍⵍⵉ ⴼ ⵜⵔⵣⵣⵓⵜ ⵓⵔ ⵜⵍⵍⵉ.',
      backHome: 'ⴰⵖⵓⵍ ⵖⵔ ⵜⴰⵙⵏⴰ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ',
    },
    roles: {
      student: 'ⴰⵏⵍⵎⴰⴷ',
      club_manager: 'ⴰⵎⵙⵜⴳⴳⴰⵔ ⵏ ⵜⵎⵙⵎⵓⵏⵜ',
      admin: 'ⴰⵎⵙⵙⵓⴳⵓⵔ',
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('campus_life_lang');
    return (stored as Language) || 'fr';
  });

  React.useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('campus_life_lang', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: string | Translations = translations[language] || translations['fr'];
    
    for (const k of keys) {
      if (typeof value === 'object' && value !== null && k in value) {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};


export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
